# This pipeline relies on the analysis.yml template located in the
# repository resource descibed below
# The ref: value must point to a branch where the template exists.
resources:
  repositories:
  - repository: templates
    type: github
    endpoint: Team1-Project3
    name: 1053-August-Duet-Project-Registry/project-registry-devops
    ref: refs/heads/feature-dockerpipe

# This pipeline will trigger on commits or pull-requests made to the branch-dev 
# or main branches.  Note that complete static analysis with SonarCloud is only 
# performed on "long-lived" branches, designated as 'main' and any branch name 
# prefixed with 'branch-'.  A minimal analysis is still performed on "short-lived" 
# branches, and a special analysis is performed on pull requests.
trigger:
- branch-dev
- main
pr:
- branch-dev
- main

pool:
  vmImage: ubuntu-latest

# These variable groups are required for sonarCloud and Discord secrets to be
# available in the analysis template
# The contents of these groups that are used here are:
#  project-registry-sonarcloud: stores sonarcloud variables/secrets
#   - sonarKeyPrefix: the common prefix string for the sonar keys in the project
#       (requires a sonarCloud project key)
#   - sonarNamePrefix: the common prefix string for the project names
#   - sonarOrg: the sonar organization
#   - sonarUrlPrefix: the common prefix string for the url for the results
#  project-registry-discord: stores discord variables/secrets
#   - discordAnalysisChannel: the output channel for discord analysis info
#   - discordAnalysisKey: the webhook key associated with the above channel
variables:
- group: project-registry-sonarcloud
- group: project-registry-discord
- name: microservice
  value: gateway
- name: version
  value: undefined
- name: containerRepo
  value: jpbulloch5
- name: containerServiceConnection
  value: 'Jacob''s Docker Hub'
- name: containerUrl
  value: https://hub.docker.com/repository/docker/jpbulloch5/project-registry-gateway

stages:
- stage: build
  jobs:
  - job: analyze

    steps:
    - checkout: self
    - checkout: templates
    - template: ./templates/analysis.yml@templates
      parameters:
        microservice: gateway
        workDir: ./project-registry-gateway/
        sonarKeyPrefix: $(sonarKeyPrefix)
        sonarNamePrefix: $(sonarNamePrefix)
        sonarOrg: $(sonarOrg)
        sonarUrlPrefix: $(sonarUrlPrefix)
        discordChannel: $(discordAnalysisChannel)
        discordKey: $(discordAnalysisKey)

    displayName: Analyze --> Job

  - job: dockerize
    steps:
    - checkout: self
    - checkout: templates

    - script: |
      displayName: Install mvn-version dependencies --> Task
    
    - script: |
        sudo apt-get install zsh -y
        sudo apt-get install xmlstarlet -y
        sudo bash autogen.sh
        sudo ./configure
        sudo make
        sudo make install
      workingDirectory: $(Build.SourcesDirectory)/project-registry-devops/tools/mvn-version-1.2.1
      displayName: Install mvn-version --> Task
      
    - script: |
        VERSION=$(mvn-version .)
        echo extracted $VERSION
        echo "##vso[task.setvariable variable=version]$VERSION"
        echo exported version: $(version)
      workingDirectory: $(Build.SourcesDirectory)/project-registry-${{ variables.microservice }} 
      displayName: Extract microservice version from pom.xml file --> Task

    - task: Docker@2
      inputs:
        containerRegistry: ${{ variables.containerServiceConnection }}
        repository: '${{ variables.containerRepo }}/project-registry-${{ variables.microservice }}'
        command: 'buildAndPush'
        Dockerfile: '**/Dockerfile'
        tags: '$(version)'
      displayName: Dockerize ${{ variables.microservice }} and push --> Task
    
    - task: ado-discord-webhook@1
      inputs:
        channelId: '$(discordDockerChannel)'
        webhookKey: '$(discordDockerKey)'
        name: '$(System.TeamProject) - Docker'
        avatar: 'https://external-content.duckduckgo.com/iu/?u=https%3A%2F%2Fcdn3.iconfinder.com%2Fdata%2Ficons%2Flogos-and-brands-adobe%2F512%2F97_Docker-512.png&f=1&nofb=1'
        messageType: 'content'
        content: |
          **__Dockerization Report__**
          **Status:** $(Agent.JobStatus)
          **Branch:** $(Build.SourceBranch)
          **Trigger:** $(Build.Reason)
          **Message:** $(Build.SourceVersionMessage)
          **Image:** project-registry-${{ variables.microservice }}:$(version)
          **Container Repo:** <${{ variables.containerUrl }}>
          **Logs:** <$(System.CollectionUri)$(System.TeamProject)/_build/results?buildId=$(Build.BuildId)&view=logs>
          **Repo:** <$(Build.Repository.Uri)/tree/$(Build.SourceBranchName)>

    displayName: Dockerize --> Job

  displayName: Build --> Stage

