resources:
  repositories:
  - repository: templates
    type: github
    endpoint: Team1-Project3
    name: 1053-August-Duet-Project-Registry/project-registry-devops
    ref: refs/heads/feature-templates

trigger:
- branch-dev
- main
pr:
- branch-dev
- main

pool:
  vmImage: ubuntu-latest

variables:
- group: project-registry-sonarcloud
- group: project-registry-discord
- name: microservice
  value: "gateway"
- name: coveragePath
  value: "src/main/java/com/revature"
- name: workDir
  value: "./"
- name: maven
  value: true
- name: angular
  value: false

stages:
- stage: build
  jobs:
  - job: analyze

    steps:
    - checkout: self
    - checkout: templates
    - template: ./templates/analysis.yml@templates
      parameters:
        microservice: gateway

    displayName: Analyze --> Job

  displayName: Build --> Stage

