spring.cloud.config.enabled: false

server:
    port : 8085

spring:
  application.name: gateway
  cloud:
    config:
      discovery:
        enabled: true
        service-id: config
    
    gateway:
      routes:
        - id: account
          uri: http://localhost:8081/
          predicates:
            - Path=/api/account/**
        
        - id: project
          uri: http://localhost:8082/
          predicates:
            - Path=/api/project/**, /api/organization/**, /api/tag/**
        
        - id: tracking
          uri: http://localhost:8083/
          predicates:
            - Path=/api/status**, /api/phase/**,/api/iteration/**

      