server:
    port : 8085

spring:
  application.name: gateway_microservice
  cloud:
    config:
      discovery:
        enabled: true
        service-id: config

    consul:
      host: localhost
      port: 8500
      discovery:
        prefer-ip-address: true
    
    gateway:
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins: "http://localhost:4200"
            allowedMethods:
            - GET
            - POST
            - PUT
            - DELETE
            allowedHeaders:
            - content-type
      routes:
        - id: account
          uri: https://account:8081/
          predicates:
            - Path=/api/account/**
        
        - id: project
          uri: http://localhost:8082/
          predicates:
            - Path=/api/project/**, /api/organization/**, /api/tag/**
        
        - id: tracking
          uri: http://localhost:8083/
          predicates:
            - Path=/api/status**, /api/phase/**,/api/iteration/**
